//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ActasEntities7 : DbContext
    {
        public ActasEntities7()
            : base("name=ActasEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActasTabla> ActasTablas { get; set; }
        public virtual DbSet<Automotore> Automotores { get; set; }
        public virtual DbSet<CodInf> CodigoInfs { get; set; }
        public virtual DbSet<InfraccionxActa> InfraccionxActas { get; set; }
        public virtual DbSet<Inspectore> Inspectores { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<PersonasTemp> PersonasTemps { get; set; }
        public virtual DbSet<PersonaxActa> PersonaxActas { get; set; }
        public virtual DbSet<PersonaxAuto> PersonaxAutoes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TiposDoc> TiposDocs { get; set; }
    }
}
