//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automotore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Automotore()
        {
            this.ActasTablas = new HashSet<ActasTabla>();
            this.PersonaxAutoes = new HashSet<PersonaxAuto>();
        }
    
        public int id_automotor { get; set; }
        public string tipoAuto { get; set; }
        public string modeloAuto { get; set; }
        public string colorAuto { get; set; }
        public string patenteAuto { get; set; }
        public string marcaAuto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActasTabla> ActasTablas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaxAuto> PersonaxAutoes { get; set; }
    }
}
