//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspectore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inspectore()
        {
            this.ActasTablas = new HashSet<ActasTabla>();
        }
    
        public int id_inspector { get; set; }
        public string nombreInsp { get; set; }
        public string apellidoInsp { get; set; }
        public string direccionIPinsp { get; set; }
       
        public int rangoMinActas { get; set; }
        public int rangoMaxActas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActasTabla> ActasTablas { get; set; }
    }
}
