//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PersonasTemp
    {
        public int id_personasT { get; set; }
        [Required]
        public string nombreT { get; set; }
        public string apellidoT { get; set; }
        public string calleT { get; set; }
        public string nrocalleT { get; set; }
        public string localidadT { get; set; }
        public string documentosT { get; set; }
        public string nroDocT { get; set; }

        public int codPostalT { get; set; }

        public int NroActaT { get; set; }

    }
}
