//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.PersonaxActas = new HashSet<PersonaxActa>();
            this.PersonaxAutoes = new HashSet<PersonaxAuto>();
        }
    
        public int id_personas { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string calle { get; set; }
        public string nrocalle { get; set; }
        public string localidad { get; set; }
        public string documentos { get; set; }
        public string nroDoc { get; set; }
        public bool esTitular { get; set; }
        public bool esInfractor { get; set; }
        public bool esTutorLegal { get; set; }
        public bool esRespCivil { get; set; }
        public int codPostal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaxActa> PersonaxActas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaxAuto> PersonaxAutoes { get; set; }

        public bool eliminarDisponible { get; set; }
    }
}
