//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposDoc
    {
        public string id_tiposdoc { get; set; }
        public string documentos { get; set; }
    }
}
